In [ ]:
Section A — Exception Handling

In [ ]:
1. Write a function safe_divide(a, b) that divides two numbers and handles 
ZeroDivisionError and TypeError separately, printing an appropriate message 
for each. Use a finally block to print 'Operation attempted.' regardless of the 
outcome. Test it with valid numbers, division by zero, and a string input.

In [1]:
def safe_divide(a, b):
    try:
        result = a / b
        print("Result:", result)
    except ZeroDivisionError:
        print("Error: Cannot divide by zero.")
    except TypeError:
        print("Error: Both inputs must be numbers.")
    finally:
        print("Operation attempted.")

# Testing the function
print("Test 1: Valid numbers")
safe_divide(10, 2)

print("\nTest 2: Division by zero")
safe_divide(10, 0)

print("\nTest 3: String input")
safe_divide(10, "2")

Test 1: Valid numbers
Result: 5.0
Operation attempted.

Test 2: Division by zero
Error: Cannot divide by zero.
Operation attempted.

Test 3: String input
Error: Both inputs must be numbers.
Operation attempted.


In [ ]:
2. Write a function validate_age(age) that raises a custom exception InvalidAgeError 
(a class you define, inheriting from Exception) if age is negative or greater than 
120. Catch this exception in a calling block and print a user-friendly message. Test it with 
at least 3 different values.

In [3]:
# Custom exception class
class InvalidAgeError(Exception):
    pass

def validate_age(age):
    if age < 0:
        raise InvalidAgeError("Age cannot be negative.")
    if age > 120:
        raise InvalidAgeError("Age cannot be greater than 120.")
    print(f"Valid age: {age}")

# Testing with 3 different values
test_ages = [25, -5, 150]

for age in test_ages:
    try:
        validate_age(age)
    except InvalidAgeError as e:
        print(f"Error: {e}")

Valid age: 25
Error: Age cannot be negative.
Error: Age cannot be greater than 120.


In [ ]:
3. Write a program that repeatedly asks the user (use a loop with at least 3 simulated 
inputs in a list, e.g., user_inputs = ['10', 'abc', '0', '5']) to enter a number and 
divide 100 by it. Handle the following in a single try block using multiple except clauses:
a) ValueError if the input is not a number.  
b) ZeroDivisionError if the input is zero.  
c) A generic Exception as a catch-all for anything else.  

Print the result if successful, otherwise print which error occurred.

In [4]:
user_inputs = ['10', 'abc', '0', '5']

for item in user_inputs:
    try:
        num = int(item)          
        result = 100 / num       
        print(f"100 / {num} = {result}")
    
    except ValueError:
        print(f"Error: '{item}' is not a number.")
    
    except ZeroDivisionError:
        print(f"Error: Cannot divide by zero. Input was '{item}'.")
    
    except Exception as e:
        print(f"Unexpected error with input '{item}': {e}")

100 / 10 = 10.0
Error: 'abc' is not a number.
Error: Cannot divide by zero. Input was '0'.
100 / 5 = 20.0


In [ ]:
Section B — NumPy  

In [ ]:
4. Create a 1D NumPy array of integers from 1 to 20. Perform the following:  
a) Reshape it into a 4x5 2D array.  
b) Print the sum of each row and each column.  
c) Extract all elements greater than 10 using boolean indexing.  
d) Replace all even numbers in the array with -1.

In [5]:
import numpy as np

# a) Create 1D array and reshape to 4x5
arr = np.arange(1, 21)  # array from 1 to 20
arr_2d = arr.reshape(4, 5)

print("4x5 Array:\n", arr_2d)

# b) Sum of each row and each column
print("\nSum of each row:", arr_2d.sum(axis=1))
print("Sum of each column:", arr_2d.sum(axis=0))

# c) Extract elements greater than 10 using boolean indexing
greater_than_10 = arr_2d[arr_2d > 10]
print("\nElements greater than 10:", greater_than_10)

# d) Replace all even numbers with -1
arr_2d[arr_2d % 2 == 0] = -1
print("\nArray after replacing even numbers with -1:\n", arr_2d)

4x5 Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Sum of each row: [15 40 65 90]
Sum of each column: [34 38 42 46 50]

Elements greater than 10: [11 12 13 14 15 16 17 18 19 20]

Array after replacing even numbers with -1:
 [[ 1 -1  3 -1  5]
 [-1  7 -1  9 -1]
 [11 -1 13 -1 15]
 [-1 17 -1 19 -1]]


In [ ]:
5. Create two NumPy arrays A and B as shown below and perform:  
`A = np.array([[1, 2], [3, 4]])`  
`B = np.array([[5, 6], [7, 8]])`  

a) Element-wise addition, subtraction, and multiplication.  
b) Matrix multiplication using `np.dot()` or the `@` operator.  
c) Transpose of A.  
d) The determinant and inverse of A using `np.linalg`.

In [6]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# a) Element-wise operations
print("Element-wise Addition:\n", A + B)
print("\nElement-wise Subtraction:\n", A - B)
print("\nElement-wise Multiplication:\n", A * B)

# b) Matrix multiplication
print("\nMatrix Multiplication using @:\n", A @ B)
print("\nMatrix Multiplication using np.dot():\n", np.dot(A, B))

# c) Transpose of A
print("\nTranspose of A:\n", A.T)

# d) Determinant and inverse of A
det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A)

print(f"\nDeterminant of A: {det_A:.2f}")
print("\nInverse of A:\n", inv_A)

Element-wise Addition:
 [[ 6  8]
 [10 12]]

Element-wise Subtraction:
 [[-4 -4]
 [-4 -4]]

Element-wise Multiplication:
 [[ 5 12]
 [21 32]]

Matrix Multiplication using @:
 [[19 22]
 [43 50]]

Matrix Multiplication using np.dot():
 [[19 22]
 [43 50]]

Transpose of A:
 [[1 3]
 [2 4]]

Determinant of A: -2.00

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
6. Generate a NumPy array of 15 random integers between 1 and 100 using `np.random.randint()` (set a seed of 42 for reproducibility). Then:  
a) Find the mean, median, standard deviation, min, and max.  
b) Sort the array in descending order.  
c) Find the indices of the 3 largest values using `np.argsort()`.  
d) Normalize the array so all values lie between 0 and 1.

In [7]:
import numpy as np

np.random.seed(42)
arr = np.random.randint(1, 101, size=15)

print("Original Array:\n", arr)

print("\nMean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Min:", np.min(arr))
print("Max:", np.max(arr))

desc_sorted = np.sort(arr)[::-1]
print("\nSorted in Descending Order:\n", desc_sorted)

indices_3_largest = np.argsort(arr)[-3:][::-1]
print("\nIndices of 3 largest values:", indices_3_largest)
print("3 largest values:", arr[indices_3_largest])

normalized = (arr - arr.min()) / (arr.max() - arr.min())
print("\nNormalized Array (0 to 1):\n", normalized)

Original Array:
 [ 52  93  15  72  61  21  83  87  75  75  88 100  24   3  22]

Mean: 58.06666666666667
Median: 72.0
Standard Deviation: 31.4843170836247
Min: 3
Max: 100

Sorted in Descending Order:
 [100  93  88  87  83  75  75  72  61  52  24  22  21  15   3]

Indices of 3 largest values: [11  1 10]
3 largest values: [100  93  88]

Normalized Array (0 to 1):
 [0.50515464 0.92783505 0.12371134 0.71134021 0.59793814 0.18556701
 0.82474227 0.86597938 0.74226804 0.74226804 0.87628866 1.
 0.21649485 0.         0.19587629]


In [ ]:
Section C — Pandas Basics  

In [ ]:
7. Create a Pandas DataFrame from the dictionary below and perform the following:
data = { "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"], 
         "Age": [23, 21, 25, 22, 24], 
         "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"], 
         "Score": [88, 92, 79, 95, 67], }
a) Display the first 3 rows and the data types of each column.  
b) Add a new column Grade based on Score (>=90 'A', >=75 'B', else 'C').  
c) Sort the DataFrame by Score in descending order.  
d) Filter rows where Department is 'AI'.

In [8]:
import pandas as pd

data = { "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"], 
         "Age": [23, 21, 25, 22, 24], 
         "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"], 
         "Score": [88, 92, 79, 95, 67], }

df = pd.DataFrame(data)

print("First 3 rows:\n", df.head(3))
print("\nData types:\n", df.dtypes)

df['Grade'] = df['Score'].apply(lambda x: 'A' if x >= 90 else 'B' if x >= 75 else 'C')
print("\nDataFrame with Grade column:\n", df)

df_sorted = df.sort_values(by='Score', ascending=False)
print("\nSorted by Score (descending):\n", df_sorted)

df_ai = df[df['Department'] == 'AI']
print("\nRows where Department is 'AI':\n", df_ai)

First 3 rows:
     Name  Age    Department  Score
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79

Data types:
 Name          object
Age            int64
Department    object
Score          int64
dtype: object

DataFrame with Grade column:
     Name  Age    Department  Score Grade
0  Aarav   23            AI     88     B
1  Priya   21  Data Science     92     A
2  Karan   25            AI     79     B
3  Meera   22       Web Dev     95     A
4  Sahil   24  Data Science     67     C

Sorted by Score (descending):
     Name  Age    Department  Score Grade
3  Meera   22       Web Dev     95     A
1  Priya   21  Data Science     92     A
0  Aarav   23            AI     88     B
2  Karan   25            AI     79     B
4  Sahil   24  Data Science     67     C

Rows where Department is 'AI':
     Name  Age Department  Score Grade
0  Aarav   23         AI     88     B
2  Karan   25         AI     79     B


In [ ]:
8. Using the same DataFrame from Q7:
a) Group by Department and find the average Score for each.  
b) Find the row with the highest Score using `idxmax()`.  
c) Rename the column Score to Marks.  
d) Drop the Age column and display the resulting DataFrame.

In [10]:
import pandas as pd

# DataFrame from Q7
data = { "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"], 
         "Age": [23, 21, 25, 22, 24], 
         "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"], 
         "Score": [88, 92, 79, 95, 67], }

df = pd.DataFrame(data)

# a) Group by Department and find average Score
avg_score = df.groupby('Department')['Score'].mean()
print("Average Score by Department:\n", avg_score)

# b) Row with highest Score using idxmax()
idx_max = df['Score'].idxmax()
highest_row = df.loc[idx_max]
print("\nRow with highest Score:\n", highest_row)

# c) Rename Score to Marks
df = df.rename(columns={'Score': 'Marks'})
print("\nDataFrame after renaming Score to Marks:\n", df.head())

# d) Drop Age column
df = df.drop(columns=['Age'])
print("\nFinal DataFrame after dropping Age:\n", df)

Average Score by Department:
 Department
AI              83.5
Data Science    79.5
Web Dev         95.0
Name: Score, dtype: float64

Row with highest Score:
 Name            Meera
Age                22
Department    Web Dev
Score              95
Name: 3, dtype: object

DataFrame after renaming Score to Marks:
     Name  Age    Department  Marks
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79
3  Meera   22       Web Dev     95
4  Sahil   24  Data Science     67

Final DataFrame after dropping Age:
     Name    Department  Marks
0  Aarav            AI     88
1  Priya  Data Science     92
2  Karan            AI     79
3  Meera       Web Dev     95
4  Sahil  Data Science     67


In [ ]:
9. Create a DataFrame with some missing values as shown below and handle them:*
import numpy as np
data = { "Product": ["Pen", "Notebook", "Eraser", "Sharpener", "Ruler"],
         "Price": [10, np.nan, 5, 8, np.nan],
         "Stock": [100, 50, np.nan, 30, 20], }
a) Check the number of missing values in each column using `isnull().sum()`.  
b) Fill missing Price values with the column mean.  
c) Drop rows where Stock is still missing.  
d) Save the cleaned DataFrame to a CSV file named `cleaned_products.csv` without the index.

In [11]:
import pandas as pd
import numpy as np

data = { "Product": ["Pen", "Notebook", "Eraser", "Sharpener", "Ruler"],
         "Price": [10, np.nan, 5, 8, np.nan],
         "Stock": [100, 50, np.nan, 30, 20], }

df = pd.DataFrame(data)

# a) Check missing values in each column
print("Missing values per column:\n", df.isnull().sum())

# b) Fill missing Price values with column mean
price_mean = df['Price'].mean()
df['Price'] = df['Price'].fillna(price_mean)
print("\nAfter filling Price with mean:\n", df)

# c) Drop rows where Stock is still missing
df = df.dropna(subset=['Stock'])
print("\nAfter dropping rows with missing Stock:\n", df)

# d) Save to CSV without index
df.to_csv('cleaned_products.csv', index=False)
print("\nSaved to cleaned_products.csv")

Missing values per column:
 Product    0
Price      2
Stock      1
dtype: int64

After filling Price with mean:
      Product      Price  Stock
0        Pen  10.000000  100.0
1   Notebook   7.666667   50.0
2     Eraser   5.000000    NaN
3  Sharpener   8.000000   30.0
4      Ruler   7.666667   20.0

After dropping rows with missing Stock:
      Product      Price  Stock
0        Pen  10.000000  100.0
1   Notebook   7.666667   50.0
3  Sharpener   8.000000   30.0
4      Ruler   7.666667   20.0

Saved to cleaned_products.csv


In [ ]:
10. Read the CSV file created in Q9 (`cleaned_products.csv`) back into a new DataFrame and:*

a) Print its shape and column names.  
b) Add a new column `Total_Value` as Price multiplied by Stock.  
c) Use `describe()` to print summary statistics of the numeric columns.  
d) Wrap the file reading step in a try-except block to handle the case where the file does not exist (`FileNotFoundError`).

In [12]:
import pandas as pd

# d) Try-except block for file reading
try:
    # a) Read CSV and print shape, column names
    df = pd.read_csv('cleaned_products.csv')
    print("DataFrame loaded successfully!\n")
    
    print("Shape of DataFrame:", df.shape)
    print("Column names:", list(df.columns))
    
    # b) Add Total_Value = Price * Stock
    df['Total_Value'] = df['Price'] * df['Stock']
    print("\nDataFrame with Total_Value column:\n", df)
    
    # c) Summary statistics for numeric columns
    print("\nSummary statistics:\n", df.describe())

except FileNotFoundError:
    print("Error: cleaned_products.csv file not found!")
    print("Please run Q9 first to create the file.")

DataFrame loaded successfully!

Shape of DataFrame: (4, 3)
Column names: ['Product', 'Price', 'Stock']

DataFrame with Total_Value column:
      Product      Price  Stock  Total_Value
0        Pen  10.000000  100.0  1000.000000
1   Notebook   7.666667   50.0   383.333333
2  Sharpener   8.000000   30.0   240.000000
3      Ruler   7.666667   20.0   153.333333

Summary statistics:
            Price       Stock  Total_Value
count   4.000000    4.000000     4.000000
mean    8.333333   50.000000   444.166667
std     1.122167   35.590261   382.500303
min     7.666667   20.000000   153.333333
25%     7.666667   27.500000   218.333333
50%     7.833333   40.000000   311.666667
75%     8.500000   62.500000   537.500000
max    10.000000  100.000000  1000.000000
